import IconFacebook from "../assets/footer/IconFacebook";
import IconInstagram from "../assets/footer/IconInstagram";
import IconTwitter from "../assets/footer/IconTwitter";
import IconLinkedin from "../assets/footer/IconLinkedin";
import GamePad from "../assets/images/GamePad.svg";
import Keyboard from "../assets/images/Keyboard.svg";
import Monitor from "../assets/images/Monitor.svg";
import ComfortChair from "../assets/images/ComfortChair.svg";

import CellPhoneIcon from "../assets/category/CellPhoneIcon";
import ComputerIcon from "../assets/category/ComputerIcon";
import SmartWatchIcon from "../assets/category/SmartWatchIcon";
import CameraIcon from "../assets/category/CameraIcon";
import HeadPhoneIcon from "../assets/category/HeadphoneIcon";
import GamePadIcons from "../assets/category/GamePadIcons";

import NorthCoat from "../assets/images/NorthCoat.svg";
import DuffleBag from "../assets/images/DuffleBag.svg";
import CpuCooler from "../assets/images/CpuCooler.svg";
import SmallBookShelf from "../assets/images/SmallBookShelf.svg";

import BreedDryDogFood from "../assets/images/BreedDryDogFood.svg";
import Camera from "../assets/images/Camera.svg";
import Laptop from "../assets/images/Laptop.svg";
import Curology from "../assets/images/Curology.svg";
import ElectricCar from "../assets/images/ElectricCar.svg";
import SoccerCleats from "../assets/images/SoccerCleats.svg";
import GP11 from "../assets/images/GP11.svg";
import SatinJacket from "../assets/images/SatinJacket.svg";

import Grid from "../assets/dashboard/Grid";
import Users from "../assets/dashboard/Users";
import Setting from "../assets/dashboard/Setting";
import ShippingTruck from "../assets/dashboard/ShippingTruck";
import CartIcon from "../assets/nav/CartIcon";
import CreditCard from "../assets/dashboard/CreditCard";
import LogoutIcon from "../assets/LogoutIcon";

export const socials = [
  {
    name: "Facebook",
    icon: <IconFacebook />,
    url: "https://www.facebook.com/your-page",
  },
  {
    name: "Instagram",
    icon: <IconInstagram />,
    url: "https://www.instagram.com/your-profile",
  },
  {
    name: "X",
    icon: <IconTwitter />,
    url: "https://www.twitter.com/your-handle",
  },
  {
    name: "LinkedIn",
    icon: <IconLinkedin />,
    url: "https://www.linkedin.com/in/your-profile",
  },
];

export const footerLinks = {
  account: [
    { name: "My Account", link: "/account" },
    { name: "Login / Register", link: "/login" },
    { name: "Cart", link: "/cart" },
    { name: "Wishlist", link: "/wishlist" },
    { name: "Shop", link: "/shop" },
  ],
  quickLinks: [
    { name: "Privacy Policy", link: "/privacy-policy" },
    { name: "Terms Of Use", link: "/terms-of-use" },
    { name: "FAQ", link: "/faq" },
    { name: "Contact", link: "/contact" },
  ],
};
export const categories = [
  { name: "Phones", icon: <CellPhoneIcon />, isSelected: false },
  { name: "Computers", icon: <ComputerIcon />, isSelected: false },
  { name: "SmartWatch", icon: <SmartWatchIcon />, isSelected: false },
  { name: "Camera", icon: <CameraIcon />, isSelected: true },
  { name: "HeadPhones", icon: <HeadPhoneIcon />, isSelected: false },
  { name: "Gaming", icon: <GamePadIcons />, isSelected: false },
];

export const flashSaleProducts = [
  {
    id: 1,
    name: "HAVIT HV-G92 Gamepad",
    price: 160,
    discountPrice: 120,
    discount: 40,
    images: [GamePad],
    rating: 4.5,
    reviews: 88,
    name: "HAVIT HV-G92 Gamepad",
  },
  {
    id: 2,
    name: "AK-900 Wired Keyboard",
    price: 1160,
    discountPrice: 960,
    discount: 35,
    images: [Keyboard],
    rating: 4,
    reviews: 75,
    name: "AK-900 Wired Keyboard",
  },
  {
    id: 3,
    name: "IPS LCD Gaming Monitor",
    price: 400,
    discountPrice: 370,
    discount: 30,
    images: [Monitor],
    rating: 5,
    reviews: 99,
    name: "IPS LCD Gaming Monitor",
  },
  {
    id: 4,
    name: "S-Series Comfort Chair",
    price: 400,
    discountPrice: 375,
    discount: 25,
    images: [ComfortChair],
    rating: 4.5,
    reviews: 99,
    name: "S-Series Comfort Chair",
  },
];

export const bestproduct = [
  {
    id: 5,
    image: NorthCoat,
    name: "The north coat",
    discountPrice: 260,
    price: 360,
    rating: 5,
    reviews: 65,
  },
  {
    id: 6,
    image: DuffleBag,
    name: "Gucci duffle bag",
    discountPrice: 960,
    price: 1160,
    rating: 4.5,
    reviews: 65,
  },
  {
    id: 7,
    image: CpuCooler,
    name: "RGB liquid CPU Cooler",
    discountPrice: 160,
    price: 170,
    rating: 4.5,
    reviews: 65,
  },
  {
    id: 8,
    image: SmallBookShelf,
    name: "Small Book Shelf",
    discountPrice: 360,
    price: null,
    rating: 5,
    reviews: 65,
  },
];
export const ourproduct = [
  {
    id: 9,
    name: "Breed Dry Dog Food",
    price: "100",
    rating: 35,
    isNew: false,
    image: BreedDryDogFood,
    rating: 3,
    reviews: 35,
  },
  {
    id: 10,
    name: "CANON EOS DSLR Camera",
    price: "360",
    rating: 95,
    isNew: false,
    image: Camera,
    rating: 4,
    reviews: 95,
  },
  {
    id: 11,
    name: "ASUS FHD Gaming Laptop",
    price: "700",
    rating: 325,
    isNew: false,
    image: Laptop,
    rating: 5,
    reviews: 325,
  },
  {
    id: 12,
    name: "Curology Product Set",
    price: "500",
    rating: 145,
    isNew: false,
    image: Curology,
    rating: 5,
    reviews: 145,
  },
  {
    id: 13,
    name: "Kids Electric Car",
    price: "960",
    rating: 65,
    isNew: true,
    image: ElectricCar,
    rating: 5,
    reviews: 65,
  },
  {
    id: 14,
    name: "Jr. Zoom Soccer Cleats",
    price: "1160",
    rating: 35,
    isNew: false,
    image: SoccerCleats,
    rating: 5,
    reviews: 35,
  },
  {
    id: 15,
    name: "GP11 Shooter USB Gamepad",
    price: "660",
    rating: 55,
    isNew: true,
    image: GP11,
    rating: 4.5,
    reviews: 55,
  },
  {
    id: 16,
    name: "Quilted Satin Jacket",
    price: "660",
    rating: 55,
    isNew: false,
    image: SatinJacket,
    rating: 4.5,
    reviews: 55,
  },
];
export const wishlistProducts = [
  {
    id: 1,
    name: "Gucci duffle bag",
    discountPrice: 960,
    price: 1160,
    discount: "35%",
    image: DuffleBag,
  },
  {
    id: 2,
    name: "RGB liquid CPU Cooler",
    price: 1960,
    image: CpuCooler,
  },
  {
    id: 3,
    name: "GP11 Shooter USB Gamepad",
    price: 550,
    image: GamePad,
  },
  {
    id: 4,
    name: "Quilted Satin Jacket",
    price: 750,
    image: SatinJacket,
  },
];

export const recommendedProducts = [
  {
    id: 1,
    name: "ASUS FHD Gaming Laptop",
    discountPrice: 960,
    price: 1160,
    discount: "35%",
    image: Laptop,
    rating: 5,
    reviews: 65,
  },
  {
    id: 2,
    name: "IPS LCD Gaming Monitor",
    price: 1160,
    image: Monitor,
    rating: 5,
    reviews: 65,
  },
  {
    id: 3,
    name: "HAVIT HV-G92 Gamepad",
    price: 560,
    image: GamePad,
    rating: 5,
    reviews: 65,
  },
  {
    id: 4,
    name: "AK-900 Wired Keyboard",
    price: 200,
    image: Keyboard,
    rating: 5,
    reviews: 65,
  },
];

export const products = [
  {
    id: 1,
    name: "HAVIT HV-G92 Gamepad",
    price: 160,
    discountPrice: 120,
    discount: 40,
    discountType: "Flat",
    stock: 100,
    description:
      "Ergonomic gamepad with advanced vibration feedback for gamers.",
    sizes: ["Standard"],
    images: [GamePad],
    rating: 4.5,
    reviews: 88,
    inStock: true,
    category: "gaming",
    dateAdded: "2024-12-01",
    sku: "GAM-001",
    purchases: 120,
  },
  {
    id: 2,
    name: "AK-900 Wired Keyboard",
    price: 1160,
    discountPrice: 960,
    discount: 35,
    discountType: "Flat",
    stock: 50,
    description:
      "Compact wired keyboard with customizable keys for enhanced productivity.",
    sizes: ["Standard"],
    images: [Keyboard],
    rating: 4,
    reviews: 75,
    inStock: true,
    category: "accessories",
    dateAdded: "2024-12-01",
    sku: "ACC-002",
    purchases: 95,
  },
  {
    id: 3,
    name: "IPS LCD Gaming Monitor",
    price: 400,
    discountPrice: 370,
    discount: 30,
    discountType: "Flat",
    stock: 30,
    description: "Full HD gaming monitor with low latency and vivid colors.",
    sizes: ["24-inch", "27-inch"],
    images: [Monitor],
    rating: 5,
    reviews: 99,
    inStock: true,
    category: "accessories",
    dateAdded: "2024-12-02",
    sku: "MON-003",
    purchases: 150,
  },
  {
    id: 4,
    name: "S-Series Comfort Chair",
    price: 400,
    discountPrice: 375,
    discount: 25,
    discountType: "Flat",
    stock: 40,
    description: "Ergonomic chair with lumbar support for maximum comfort.",
    sizes: ["Standard", "Large"],
    images: [ComfortChair],
    rating: 4.5,
    reviews: 99,
    inStock: true,
    category: "furniture",
    dateAdded: "2024-12-02",
    sku: "FUR-004",
    purchases: 85,
  },
  {
    id: 5,
    name: "The North Coat",
    price: 360,
    discountPrice: 260,
    discount: 28,
    discountType: "Percentage",
    stock: 0,
    description: "Winter coat designed for warmth and style.",
    sizes: ["M", "L", "XL"],
    images: [NorthCoat],
    rating: 5,
    reviews: 65,
    inStock: false,
    category: "fashion",
    dateAdded: "2024-12-03",
    sku: "FAS-005",
    purchases: 40,
  },
  {
    id: 6,
    name: "Gucci Duffle Bag",
    price: 1160,
    discountPrice: 960,
    discount: 17,
    discountType: "Percentage",
    stock: 25,
    description: "Luxury duffle bag with a sleek and stylish design.",
    sizes: ["Standard"],
    images: [DuffleBag],
    rating: 4.5,
    reviews: 65,
    inStock: true,
    category: "fashion",
    dateAdded: "2024-12-03",
    sku: "FAS-006",
    purchases: 70,
  },
  {
    id: 7,
    name: "RGB Liquid CPU Cooler",
    price: 170,
    discountPrice: 160,
    discount: 6,
    discountType: "Percentage",
    stock: 20,
    description: "Efficient CPU cooling system with customizable RGB lighting.",
    sizes: ["Standard"],
    images: [CpuCooler],
    rating: 4.5,
    reviews: 65,
    inStock: true,
    category: "electronics",
    dateAdded: "2024-12-04",
    sku: "ELE-007",
    purchases: 110,
  },
  {
    id: 8,
    name: "Small Book Shelf",
    price: 360,
    discountPrice: 340,
    discount: 5,
    discountType: "Percentage",
    stock: 15,
    description: "Compact bookshelf perfect for small spaces.",
    sizes: ["Standard"],
    images: [SmallBookShelf],
    rating: 5,
    reviews: 65,
    inStock: true,
    category: "furniture",
    dateAdded: "2024-12-04",
    sku: "FUR-008",
    purchases: 90,
  },
  {
    id: 9,
    name: "Breed Dry Dog Food",
    price: 100,
    discountPrice: 95,
    discount: 5,
    discountType: "Percentage",
    stock: 0,
    description: "High-quality dry dog food for all breeds.",
    sizes: ["5kg", "10kg"],
    images: [BreedDryDogFood],
    rating: 3,
    reviews: 35,
    inStock: false,
    category: "petsupplies",
    dateAdded: "2024-12-04",
    sku: "PET-009",
    purchases: 50,
  },
  {
    id: 10,
    name: "CANON EOS DSLR Camera",
    price: 360,
    discountPrice: 340,
    discount: 5,
    discountType: "Percentage",
    stock: 40,
    description: "High-resolution DSLR camera for professionals.",
    sizes: ["Standard"],
    images: [Camera],
    rating: 4,
    reviews: 95,
    inStock: true,
    category: "electronics",
    dateAdded: "2024-12-04",
    sku: "ELE-010",
    purchases: 200,
  },
  {
    id: 11,
    name: "ASUS FHD Gaming Laptop",
    price: 700,
    discountPrice: 650,
    discount: 7,
    discountType: "Percentage",
    stock: 0,
    description: "High-performance laptop for gaming and multitasking.",
    sizes: ["15-inch", "17-inch"],
    images: [Laptop],
    rating: 5,
    reviews: 325,
    inStock: false,
    category: "electronics",
    dateAdded: "2024-12-04",
    sku: "ELE-011",
    purchases: 170,
  },
  {
    id: 12,
    name: "Curology Product Set",
    price: 500,
    discountPrice: 450,
    discount: 10,
    discountType: "Percentage",
    stock: 30,
    description: "Skin care set tailored for glowing skin.",
    sizes: ["Standard"],
    images: [Curology],
    rating: 5,
    reviews: 145,
    inStock: true,
    category: "beauty",
    dateAdded: "2024-12-04",
    sku: "BEA-012",
    purchases: 90,
  },
  {
    id: 13,
    name: "Kids Electric Car",
    price: 960,
    discountPrice: 860,
    discount: 10,
    discountType: "Percentage",
    stock: 10,
    description: "Electric car for kids with advanced safety features.",
    sizes: ["Standard"],
    images: [ElectricCar],
    rating: 5,
    reviews: 65,
    inStock: true,
    category: "toy",
    dateAdded: "2024-12-04",
    sku: "TOY-013",
    purchases: 75,
  },
  {
    id: 14,
    name: "Jr. Zoom Soccer Cleats",
    price: 1160,
    discountPrice: 1000,
    discount: 14,
    discountType: "Percentage",
    stock: 50,
    description: "High-quality soccer cleats for juniors.",
    sizes: ["6", "7", "8", "9"],
    images: [SoccerCleats],
    rating: 5,
    reviews: 35,
    inStock: true,
    category: "sports",
    dateAdded: "2024-12-04",
    sku: "SPR-014",
    purchases: 60,
  },
  {
    id: 15,
    name: "GP11 Shooter USB Gamepad",
    price: 660,
    discountPrice: 600,
    discount: 9,
    discountType: "Percentage",
    stock: 30,
    description: "Precision gamepad with advanced button mapping.",
    sizes: ["Standard"],
    images: [GP11],
    rating: 4.5,
    reviews: 55,
    inStock: true,
    category: "gaming",
    dateAdded: "2024-12-04",
    sku: "GAM-015",
    purchases: 95,
  },
  {
    id: 16,
    name: "Quilted Satin Jacket",
    price: 660,
    discountPrice: 600,
    discount: 9,
    discountType: "Percentage",
    stock: 20,
    description: "Stylish quilted satin jacket for all seasons.",
    sizes: ["M", "L", "XL"],
    images: [SatinJacket],
    rating: 4.5,
    reviews: 55,
    inStock: true,
    category: "fashion",
    dateAdded: "2024-12-04",
    sku: "FAS-016",
    purchases: 80,
  },
];

export const adminSidebarItems = [
  { name: "Dashboard", icon: <Grid />, path: "/admin" },
  { name: "Product", icon: <Grid />, path: "/admin/product" },
  { name: "Customers", icon: <Users />, path: "/admin/customers" },
  { name: "Vendors", icon: <Users />, path: "/admin/vendor" },
  { name: "Order", icon: <CartIcon />, path: "/admin/orders" },
  { name: "Shipment", icon: <ShippingTruck />, path: "/admin/shipments" },
  { name: "Transactions", icon: <CreditCard />, path: "/admin/transactions" },
  { name: "Setting", icon: <Setting />, path: "admin/settings" },
];

export const vendorSidebarItems = [
  { name: "Dashboard", icon: <Grid />, path: "/vendorpage" },
  { name: "Product", icon: <Grid />, path: "/vendorpage/product" },
  { name: "Order", icon: <CartIcon />, path: "/vendorpage/orders" },
  { name: "Shipment", icon: <ShippingTruck />, path: "/vendorpage/shipments" },
  {
    name: "Transactions",
    icon: <CreditCard />,
    path: "/vendorpage/transactions",
  },
  { name: "Setting", icon: <Setting />, path: "/vendorpage/settings" },
];
